# https://www.elliotdenolf.com/posts/build-net-5-applications-with-github-actions/
# https://swimburger.net/blog/dotnet/how-to-deploy-aspnet-blazor-webassembly-to-github-pages

name: .NET 5 CI
on: 
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest #https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

    name: .NET 5 App build and publish to GitHub Pages

    steps:

      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.x'

      - name: build the app via publish profile
        run: dotnet build -c Release /p:DeployOnBuild=true /p:PublishProfile=ClickOnceProfile # https://stackoverflow.com/questions/62787426/dotnet-publish-profile-ignores-pubxml-file/62954314#62954314

      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5 # https://github.com/JamesIves/github-pages-deploy-action/releases
        with:
          branch: gh-pages
          folder: bin/publish
