# https://www.elliotdenolf.com/posts/build-net-5-applications-with-github-actions/
# https://swimburger.net/blog/dotnet/how-to-deploy-aspnet-blazor-webassembly-to-github-pages

name: .NET 5 CI
on: 
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest #https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

    name: .NET 5 App build and publish to GitHub Pages

    steps:

      - uses: actions/checkout@v2

#       - name: Setup dotnet
#         uses: actions/setup-dotnet@v1
#         with:
#           dotnet-version: '5.x'
          
      # resolves: MSB4803: The task "FormatUrl" is not supported on the .NET Core version of MSBuild. Please use the .NET Framework version of MSBuild.  
      - name: Add .net msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.3          
        
#       - name: dotnet restore
#         run: dotnet restore

      - name: build the app via publish profile
        #run: dotnet build -c Release /p:DeployOnBuild=true /p:PublishProfile=ClickOnceProfile # https://stackoverflow.com/questions/62787426/dotnet-publish-profile-ignores-pubxml-file/62954314#62954314
        #run: dotnet publish -p:PublishProfile=ClickOnceProfile #https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish#msbuild
        # https://stackoverflow.com/questions/13920146/using-msbuild-exe-to-publish-a-asp-net-mvc-4-project-with-the-cmd-line/61926970#61926970
        #common bad recommend: run: msbuild VipLeagueWpf.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=ClickOnceProfile
        #https://stackoverflow.com/questions/16246562/using-msbuild-to-execute-a-file-system-publish-profile/54094398#54094398
        run: msbuild /t:restore,publish /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=ClickOnceProfile.pubxml

      - name: Commit new build to GitHub Pages
        #this one had an rsync dependency not present on windows: uses: JamesIves/github-pages-deploy-action@4.1.5 # https://github.com/JamesIves/github-pages-deploy-action/releases
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./VipLeagueWpf/bin/Release/net5.0-windows/win-x64/app.publish
